// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Input.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
public:
  Fl_Check_Button *FlagB;
private:
  void cb_FlagB_i(Fl_Check_Button*, void*);
  static void cb_FlagB(Fl_Check_Button*, void*);
public:
  Fl_Button *LoadButton;
private:
  void cb_LoadButton_i(Fl_Button*, void*);
  static void cb_LoadButton(Fl_Button*, void*);
public:
  Fl_Button *SaveButton;
private:
  void cb_SaveButton_i(Fl_Button*, void*);
  static void cb_SaveButton(Fl_Button*, void*);
public:
  Fl_Button *EdgeDetect;
private:
  void cb_EdgeDetect_i(Fl_Button*, void*);
  static void cb_EdgeDetect(Fl_Button*, void*);
public:
  Fl_Input *AdjBrightness;
private:
  void cb_AdjBrightness_i(Fl_Input*, void*);
  static void cb_AdjBrightness(Fl_Input*, void*);
public:
  void show();
  void DBG_cb();
  void FlagB_cb();
  void LoadButton_cb();
  void SaveButton_cb();
  void AdjBrightness_cb();
  void EdgeDetect_cb();
};
#endif
