// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
public:
  Fl_Check_Button *FlagB;
private:
  void cb_FlagB_i(Fl_Check_Button*, void*);
  static void cb_FlagB(Fl_Check_Button*, void*);
public:
  void show();
  void DBG_cb();
  void FlagB_cb();
};
#endif
