// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef tmp_h
#define tmp_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_File_Input.H>

class UserInterface : public Fl_Group {
public:
  UserInterface(int X, int Y, int W, int H, const char *L = 0);
  Fl_File_Input *TextureFile;
private:
  void cb_TextureFile_i(Fl_File_Input*, void*);
  static void cb_TextureFile(Fl_File_Input*, void*);
};
#endif
