// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "gui.h"

void GUI::cb_Load_i(Fl_Button*, void*) {
  LoadFile_cb();
}
void GUI::cb_Load(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

void GUI::cb_LoadFile_i(Fl_File_Input*, void*) {
  ReadFile_cb();
}
void GUI::cb_LoadFile(Fl_File_Input* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_LoadFile_i(o,v);
}

void GUI::cb_SaveFile_i(Fl_File_Input*, void*) {
  SaveTo_cb();
}
void GUI::cb_SaveFile(Fl_File_Input* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_SaveFile_i(o,v);
}

void GUI::cb_Save_i(Fl_Button*, void*) {
  Save_cb();
}
void GUI::cb_Save(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Save_i(o,v);
}

void GUI::cb_Adjust_i(Fl_Button*, void*) {
  AdjustBrightness_cb();
}
void GUI::cb_Adjust(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Adjust_i(o,v);
}

void GUI::cb_VisualizeButton_i(Fl_Button*, void*) {
  visual_cb();
}
void GUI::cb_VisualizeButton(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_VisualizeButton_i(o,v);
}

void GUI::cb_Up_i(Fl_Button*, void*) {
  up_cb();
}
void GUI::cb_Up(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Up_i(o,v);
}

void GUI::cb_Down_i(Fl_Button*, void*) {
  down_cb();
}
void GUI::cb_Down(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Down_i(o,v);
}

void GUI::cb_Left_i(Fl_Button*, void*) {
  left_cb();
}
void GUI::cb_Left(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Left_i(o,v);
}

void GUI::cb_Right_i(Fl_Button*, void*) {
  right_cb();
}
void GUI::cb_Right(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Right_i(o,v);
}

void GUI::cb_Front_i(Fl_Button*, void*) {
  front_cb();
}
void GUI::cb_Front(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Front_i(o,v);
}

void GUI::cb_Back_i(Fl_Button*, void*) {
  back_cb();
}
void GUI::cb_Back(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Back_i(o,v);
}

void GUI::cb_Zoom_i(Fl_Button*, void*) {
  zoomin_cb();
}
void GUI::cb_Zoom(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Zoom_i(o,v);
}

void GUI::cb_Zoom1_i(Fl_Button*, void*) {
  zoomout_cb();
}
void GUI::cb_Zoom1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Zoom1_i(o,v);
}

void GUI::cb_Pan_i(Fl_Button*, void*) {
  pan_cb();
}
void GUI::cb_Pan(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Pan_i(o,v);
}

void GUI::cb_Tilt_i(Fl_Button*, void*) {
  tilt_cb();
}
void GUI::cb_Tilt(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Tilt_i(o,v);
}

void GUI::cb_Roll_i(Fl_Button*, void*) {
  roll_cb();
}
void GUI::cb_Roll(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Roll_i(o,v);
}

void GUI::cb_Play_i(Fl_Button*, void*) {
  play_cb();
}
void GUI::cb_Play(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Play_i(o,v);
}

void GUI::cb_pointLightx_i(Fl_Input*, void*) {
  pointLightx_cb();
}
void GUI::cb_pointLightx(Fl_Input* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_pointLightx_i(o,v);
}

void GUI::cb_pointLighty_i(Fl_Input*, void*) {
  pointLighty_cb();
}
void GUI::cb_pointLighty(Fl_Input* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_pointLighty_i(o,v);
}

void GUI::cb_pointLightz_i(Fl_Input*, void*) {
  pointLightz_cb();
}
void GUI::cb_pointLightz(Fl_Input* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_pointLightz_i(o,v);
}

void GUI::cb_ka_i(Fl_Input*, void*) {
  ka_cb();
}
void GUI::cb_ka(Fl_Input* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_ka_i(o,v);
}

void GUI::cb_es_i(Fl_Input*, void*) {
  es_cb();
}
void GUI::cb_es(Fl_Input* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_es_i(o,v);
}

void GUI::cb_Draw_i(Fl_Button*, void*) {
  drawPointLight_cb();
}
void GUI::cb_Draw(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Draw_i(o,v);
}

void GUI::cb_SM1_i(Fl_Button*, void*) {
  sm1_cb();
}
void GUI::cb_SM1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_SM1_i(o,v);
}

void GUI::cb_SM2_i(Fl_Button*, void*) {
  sm2_cb();
}
void GUI::cb_SM2(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_SM2_i(o,v);
}

void GUI::cb_SM3_i(Fl_Button*, void*) {
  sm3_cb();
}
void GUI::cb_SM3(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_SM3_i(o,v);
}

void GUI::cb_SM2Play_i(Fl_Button*, void*) {
  SM2Play_cb();
}
void GUI::cb_SM2Play(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_SM2Play_i(o,v);
}

void GUI::cb_SM3Play_i(Fl_Button*, void*) {
  SM3Play_cb();
}
void GUI::cb_SM3Play(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_SM3Play_i(o,v);
}

void GUI::cb_SM2SM3_i(Fl_Button*, void*) {
  SM2SM3_cb();
}
void GUI::cb_SM2SM3(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_SM2SM3_i(o,v);
}
#include "scene.h"

GUI::GUI() {
  { uiw = new Fl_Double_Window(870, 796, "Control Center");
    uiw->user_data((void*)(this));
    { Load = new Fl_Button(335, 55, 100, 45, "Load");
      Load->callback((Fl_Callback*)cb_Load);
    } // Fl_Button* Load
    { LoadFile = new Fl_File_Input(585, 648, 185, 37, "Load file:");
      LoadFile->callback((Fl_Callback*)cb_LoadFile);
    } // Fl_File_Input* LoadFile
    { SaveFile = new Fl_File_Input(495, 527, 370, 68, "Save file:");
      SaveFile->callback((Fl_Callback*)cb_SaveFile);
    } // Fl_File_Input* SaveFile
    { Save = new Fl_Button(435, 120, 85, 30, "Save");
      Save->callback((Fl_Callback*)cb_Save);
    } // Fl_Button* Save
    { Fl_Button* o = new Fl_Button(450, 185, 80, 35, "Adjust");
      o->callback((Fl_Callback*)cb_Adjust);
    } // Fl_Button* o
    { VisualizeButton = new Fl_Button(587, 293, 124, 32, "Visualize Camera");
      VisualizeButton->callback((Fl_Callback*)cb_VisualizeButton);
    } // Fl_Button* VisualizeButton
    { Fl_Button* o = new Fl_Button(615, 105, 65, 50, "Up");
      o->callback((Fl_Callback*)cb_Up);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(615, 157, 65, 50, "Down");
      o->callback((Fl_Callback*)cb_Down);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(552, 157, 58, 51, "Left");
      o->callback((Fl_Callback*)cb_Left);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(683, 154, 64, 53, "Right");
      o->callback((Fl_Callback*)cb_Right);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(550, 220, 90, 30, "Front");
      o->callback((Fl_Callback*)cb_Front);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(650, 220, 95, 30, "Back");
      o->callback((Fl_Callback*)cb_Back);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(770, 92, 64, 30, "Zoom in");
      o->callback((Fl_Callback*)cb_Zoom);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(771, 130, 64, 30, "Zoom out");
      o->callback((Fl_Callback*)cb_Zoom1);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(772, 167, 64, 30, "Pan");
      o->callback((Fl_Callback*)cb_Pan);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(772, 202, 64, 30, "Tilt");
      o->callback((Fl_Callback*)cb_Tilt);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(772, 236, 64, 30, "Roll");
      o->callback((Fl_Callback*)cb_Roll);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(588, 256, 120, 30, "Play");
      o->callback((Fl_Callback*)cb_Play);
    } // Fl_Button* o
    { pointLightx = new Fl_Input(196, 375, 59, 35, "Point light position (x,y,z):");
      pointLightx->callback((Fl_Callback*)cb_pointLightx);
    } // Fl_Input* pointLightx
    { pointLighty = new Fl_Input(255, 375, 55, 35);
      pointLighty->callback((Fl_Callback*)cb_pointLighty);
    } // Fl_Input* pointLighty
    { pointLightz = new Fl_Input(308, 375, 60, 35);
      pointLightz->callback((Fl_Callback*)cb_pointLightz);
    } // Fl_Input* pointLightz
    { ka = new Fl_Input(135, 435, 95, 30, "Ambient factor: ");
      ka->callback((Fl_Callback*)cb_ka);
    } // Fl_Input* ka
    { es = new Fl_Input(162, 470, 68, 30, "Specular exponent: ");
      es->callback((Fl_Callback*)cb_es);
    } // Fl_Input* es
    { Fl_Button* o = new Fl_Button(380, 375, 50, 30, "Draw");
      o->callback((Fl_Callback*)cb_Draw);
    } // Fl_Button* o
    { SM1 = new Fl_Button(35, 524, 55, 25, "SM1");
      SM1->callback((Fl_Callback*)cb_SM1);
    } // Fl_Button* SM1
    { SM2 = new Fl_Button(90, 524, 55, 25, "SM2");
      SM2->callback((Fl_Callback*)cb_SM2);
    } // Fl_Button* SM2
    { SM3 = new Fl_Button(145, 524, 55, 25, "SM3");
      SM3->callback((Fl_Callback*)cb_SM3);
    } // Fl_Button* SM3
    { SM2Play = new Fl_Button(305, 435, 125, 35, "SM2 Moving Light");
      SM2Play->callback((Fl_Callback*)cb_SM2Play);
    } // Fl_Button* SM2Play
    { SM3Play = new Fl_Button(305, 478, 125, 35, "SM3 Moving Light");
      SM3Play->callback((Fl_Callback*)cb_SM3Play);
    } // Fl_Button* SM3Play
    { SM2SM3 = new Fl_Button(305, 520, 125, 30, "Comparing SM2/3");
      SM2SM3->callback((Fl_Callback*)cb_SM2SM3);
    } // Fl_Button* SM2SM3
    uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();
}

void GUI::DBG_cb() {
  scene->DBG();
}

void GUI::FlagB_cb() {
  scene->FlagB();
}

void GUI::LoadFile_cb() {
  scene->LoadFile();
}

void GUI::Save_cb() {
  scene->SaveFile();
}

void GUI::SaveFile_cb() {
  scene->SaveTo();
}

void GUI::visual_cb() {
  scene->Visualize();
}

void GUI::up_cb() {
  scene->Up();
}

void GUI::down_cb() {
  scene->Down();
}

void GUI::left_cb() {
  scene->Left();
}

void GUI::right_cb() {
  scene->Right();
}

void GUI::front_cb() {
  scene->Front();
}

void GUI::back_cb() {
  scene->Back();
}

void GUI::pan_cb() {
  scene->Pan();
}

void GUI::tilt_cb() {
  scene->Tilt();
}

void GUI::roll_cb() {
  scene->Roll();
}

void GUI::zoomin_cb() {
  scene->ZoomIn();
}

void GUI::zoomout_cb() {
  scene->ZoomOut();
}

void GUI::play_cb() {
  scene->Play();
}

void GUI::pointLightx_cb() {
  scene->pointLightx();
}

void GUI::pointLighty_cb() {
  scene->pointLighty();
}

void GUI::pointLightz_cb() {
  scene->pointLightz();
}

void GUI::ka_cb() {
  scene->Ka();
}

void GUI::es_cb() {
  scene->Es();
}

void GUI::sm1_cb() {
  scene->SM1();
}

void GUI::sm2_cb() {
  scene->SM2();
}

void GUI::sm3_cb() {
  scene->SM3();
}

void GUI::drawPointLight_cb() {
  scene->DrawPointLight();
}

void GUI::SM2Play_cb() {
  scene->SM2Play();
}

void GUI::SM3Play_cb() {
  scene->SM3Play();
}

void GUI::SM2SM3_cb() {
  scene->SM2SM3();
}
